wallpaper {
    monitor = eDP-1
    path = /home/mats/.config/hypr/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/mats/.config/hypr/blue-mountains.jpg
    fit_mode = cover
}
