------------------
---- MONITORS ----
------------------

-- Loads ~/.config/hypr/monitors.lua (generated by nwg-displays)
require("monitors")


---------------------
---- MY PROGRAMS ----
---------------------

local terminal = "kitty"
local fileManager = "kitty -e yazi"
local menu = "rofi -show drun"
local fileSearch = [[sh -c 'if command -v fd >/dev/null 2>&1; then list="$(fd . "$HOME" --hidden --follow --exclude .git --exclude node_modules --exclude .cache 2>/dev/null)"; else list="$(find "$HOME" -mindepth 1 \( -path "*/.git/*" -o -path "*/node_modules/*" -o -path "*/.cache/*" \) -prune -o -print 2>/dev/null)"; fi; chosen="$(printf "%s\n" "$list" | rofi -dmenu -p "Search..." -i)"; if [ -n "$chosen" ]; then if [ -d "$chosen" ]; then code "$chosen"; else xdg-open "$chosen"; fi; fi']]
local browser = "google-chrome-stable"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("waybar & hyprpaper")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/start-clock-widget.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/workspace-border.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/volume-control.sh init")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 0,
        border_size = 2,
        col = {
            active_border = "rgba(323f4caa)",
            inactive_border = "rgba(263038aa)",
        },
        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding = 12,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 10,
            passes = 2,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "slave",
        mfact = 0.70,
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },

    input = {
        kb_layout = "no",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:super, lv3:lalt_switch,compose:rctrl",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0.35,
        accel_profile = "flat",
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- Gestures
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Device-specific configuration
hl.device({
    name = "epic-mouse-v1",
    sensitivity = 0.35,
    accel_profile = "flat",
})

-- Animation curves
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Animations
hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 1,    bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 1,    bezier = "easeOutQuint",   style = "slide down" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1,    bezier = "linear",         style = "slide up" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "linear" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 1,    bezier = "linear" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 3,    bezier = "linear",         style = "slide left" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 6,    bezier = "easeInOutCubic", style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 6,    bezier = "easeInOutCubic", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 6,    bezier = "easeInOutCubic", style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

-- Applications & Utilities
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(browser .. " --app=https://chat.deepseek.com --new-window"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(fileSearch))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + p", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("hyprshot -m region -c"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))

-- Window Focus (Vim keys)
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Workspaces 1-10
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mouse wheel
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mouse dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/volume-control.sh volume_up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/volume-control.sh volume_down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/volume-control.sh volume_mute"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/volume-control.sh mic_mute"), { locked = true, repeating = true })

-- Fn keys for volume / mute
hl.bind("F6", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/volume-control.sh volume_mute"), { locked = true, repeating = true })
hl.bind("F7", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/volume-control.sh volume_down"), { locked = true, repeating = true })
hl.bind("F8", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/volume-control.sh volume_up"), { locked = true, repeating = true })

-- Audio device switch
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/audio-device-switch.py"))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/audio-device-switch.py"))

-- LCD brightness controls
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
hl.bind("F2", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })
hl.bind("F3", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true })

-- Media player controls
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Reload waybar, hyprpaper, and eww widgets
hl.bind(mainMod .. " + SHIFT + w", hl.dsp.exec_cmd("pkill waybar; pkill hyprpaper; pkill eww; sleep 0.5; waybar & hyprpaper & " .. os.getenv("HOME") .. "/.config/hypr/scripts/start-clock-widget.sh"))

-- Open favourite game
hl.bind(mainMod .. " + z", hl.dsp.exec_cmd("steam 'steam://rungameid/686060'"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Loads ~/.config/hypr/workspaces.lua
require("workspaces")
