splash = false
# Load the image into memory first
preload = /home/mats/.config/hypr/wallpaper.jpg

# Then assign it to your monitor
wallpaper {
    monitor = #eDP-1
    path = /home/mats/.config/hypr/wallpaper.jpg
    # fit_mode = cover # Optional
}

