-- Generated by nwg-displays on 2026-10-07 at 17:32:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "540x387",
    scale = 1.5,
    vrr = 0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "2460x507",
    scale = 0.9999999999999999,
    vrr = 0
})
