-- Generated by nwg-displays on 2026-08-26 at 20:38:35. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "540x387",
    scale = 1.5
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "2460x0",
    scale = 1.1999999999999993,
    transform = 1
})
